### ISSUE TITLE
App never connects to server, no error message

### ISSUE THREAD

**Issue by CyberneticCody** [daper/nextcloud-passwords-app#61]
When opening the app for the first time, and avoiding issuse #60 the app just gets stuck "Loading..." and never does anything else.
I am using NextCloud 17.0.2 and Passwords 2020.1.0. I have a LetsEncrypt certificate and have my server configured for TLSv1.2 and TLSv1.3 only.

**Comment by selfisch** [comment]
Hi,

same here. I tested around a little bit with LDAP user integration but after some other knock backs, I turned everything back to normal/local nc user accounts. Since then, password app is not usable anymore.
Also tried to remove app and cache data on the phone. Removed the app completely, restartet the phone... nothing worked.

After starting the app and entering the server address, there is only the "loading" screen, with spinner. My nc log says nothing and the only thing I can see in my nginx log is:
```
client_ip - - [16/Feb/2020:11:04:06 +0100] "GET /ocs/v1.php/cloud/capabilities HTTP/1.1" 200 652 "-" "okhttp/3.12.1"
```

Nextcloud version 17.0.3
Android App Version: 1.11
Android Version: OnePlus 5t, Stock Oxygen 9.0.10

If this project is not supported anymore, please let us know.
Maybe, someone has a commercial, open source paid alternativ.
