### ISSUE TITLE
Network error - persistent over different phones/android 8 and 9

### ISSUE THREAD

**Issue by jfsgithub2020** [daper/nextcloud-passwords-app#66]
Dear daper, 
sorry to bother you here again: I am using Android 8.1.0 with a self signed cert for many years now and have installed the CA. Still no chance to use the password app. The server is on debian in version 18.0.2.2 Nextcloud by itself works fine a long time. Now, on another newer phone with android 9 (MIUI, Xiaomi), it shows the same problem just with nextcloud passwords. As no log files or elaborate error descritions are there I can't provide it. I am using version 1.14 and cleared all data and cache inbetween as suggested, to no avail.

Let me know, if i can help debug the problem.

Jocki

**Comment by daper** [comment]
Hi @jfsgithub2020, network error usually means that the application couldn't validate the server certificate. You could see on android via logcat. Anyways I am working on implementing the library proposed on #63, to be able to use the network stack of Nextcloud Files app and therefore bypass this "security issue". The development is very promissing... I've currently have it successfully working with the login and pull passwords and folders. So, few touches more and I will release. :tada:

I am closing your issue because I couldn't make it work with self-signed/self-created ca too and #63 makes sense to be the following point for these topics. Thank you!

**Comment by jfsgithub2020** [comment]
Thanks for explaining - now I understand #63 better. :-) I'll keep my horses rained in until next release :-)
