### ISSUE TITLE
Leading zeros are removed from password

### ISSUE THREAD

**Issue by godfuture** [daper/nextcloud-passwords-app#76]
Hi, I have set a password to something like this 0xxx where xxx are numbers != 0.

After saving the leading zero disappears.

**Comment by daper** [comment]
Hi @godfuture, can you confirm that your version is >= v1.13? As I though this was fixed on #15

**Comment by godfuture** [comment]
I have v 1.14 from fdroid installed.

**Comment by daper** [comment]
Hey @godfuture, the builds on f-droid are stuck on v1.11. They are pending this [MR-771](https://gitlab.com/fdroid/fdroidserver/-/merge_requests/771) in order to successfully compile and release. So if you don't want to install it from Google Play Store and you trust on the apks I upload, pick the latest one from here: [NextcloudPasswords.apk](https://github.com/daper/nextcloud-passwords-app/releases/download/v1.14/NextcloudPasswords.apk)

I've tested with a build I made this afternoon and it worked fine.

This closes #77 too.
